---
- name: Setup Telegraf
  docker:
    name: telegraf
    image: telegraf:1.3
    state: reloaded
    links:
      - "influxdb:influxdb"
    volumes:
      - /home/{{remote_user}}/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock

- name: Setup InfluxDB
  docker:
    name: influxdb
    image: influxdb:1.2
    state: reloaded
    ports:
      - "8083:8083"
      - "8086:8086"

- name: Setup Chronograf
  docker:
    name: chronograf
    image: chronograf:1.3
    state: reloaded
    ports:
      - "8888:8888"
    links:
      - "influxdb:influxdb"

- name: Setup Kapacitor
  docker:
    name: kapacitor
    image: kapacitor:1.2
    state: reloaded
    volumes:
      - /home/{{remote_user}}/kapacitor.conf:/etc/kapacitor/kapacitor.conf
